/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_cam_cl_xf214_blackadderWrapper_BAWrapperShared */

#ifndef _Included_uk_ac_cam_cl_xf214_blackadderWrapper_BAWrapperShared
#define _Included_uk_ac_cam_cl_xf214_blackadderWrapper_BAWrapperShared
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_cam_cl_xf214_blackadderWrapper_BAWrapperShared
 * Method:    c_hex_to_char
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_uk_ac_cam_cl_xf214_blackadderWrapper_BAWrapperShared_c_1hex_1to_1char
  (JNIEnv *, jclass, jstring);

/*
 * Class:     uk_ac_cam_cl_xf214_blackadderWrapper_BAWrapperShared
 * Method:    c_char_to_hex
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_uk_ac_cam_cl_xf214_blackadderWrapper_BAWrapperShared_c_1char_1to_1hex
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
