/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cam_androidSpeex_NativeSpeexDecoder */

#ifndef _Included_cam_androidSpeex_NativeSpeexDecoder
#define _Included_cam_androidSpeex_NativeSpeexDecoder
#ifdef __cplusplus
extern "C" {
#endif
#undef cam_androidSpeex_NativeSpeexDecoder_DEFAULT_SPEEX_MODEID
#define cam_androidSpeex_NativeSpeexDecoder_DEFAULT_SPEEX_MODEID 2L
/*
 * Class:     cam_androidSpeex_NativeSpeexDecoder
 * Method:    c_init_bits
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_cam_androidSpeex_NativeSpeexDecoder_c_1init_1bits
  (JNIEnv *, jobject);

/*
 * Class:     cam_androidSpeex_NativeSpeexDecoder
 * Method:    c_init
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_cam_androidSpeex_NativeSpeexDecoder_c_1init
  (JNIEnv *, jobject, jint);

/*
 * Class:     cam_androidSpeex_NativeSpeexDecoder
 * Method:    c_set
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_cam_androidSpeex_NativeSpeexDecoder_c_1set
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     cam_androidSpeex_NativeSpeexDecoder
 * Method:    c_get
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_cam_androidSpeex_NativeSpeexDecoder_c_1get
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cam_androidSpeex_NativeSpeexDecoder
 * Method:    c_mode_query
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cam_androidSpeex_NativeSpeexDecoder_c_1mode_1query
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     cam_androidSpeex_NativeSpeexDecoder
 * Method:    c_decode
 * Signature: (JJLjava/nio/ByteBuffer;III)[S
 */
JNIEXPORT jshortArray JNICALL Java_cam_androidSpeex_NativeSpeexDecoder_c_1decode
(JNIEnv *, jobject, jlong, jlong, jobject, jint, jint, jint);

/*
 * Class:     cam_androidSpeex_NativeSpeexDecoder
 * Method:    c_destroy
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_cam_androidSpeex_NativeSpeexDecoder_c_1destroy
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
